In [1]:
from constants import STORE_COLUMNS, INTERNET_SPEED_COLUMNS, INTERNET_SPEED_INT_COLUMNS, STORES_TABLE, INTERNET_SPEED_TABLE
from create_tables import create_tables 
from get_data.get_trader_joes import create_dataframe 
from upsert_data import upsert_dataframe_batch
from insert_data import insert_df

import pandas as pd

In [2]:
command = open("sql/create_stores.sql", "r").read()
create_tables(command)

Connected to the PostgreSQL server.
Table created successfully.
Database connection closed.

In [3]:
df = create_dataframe()

Total stores found: 647

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 647 entries, 0 to 646
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_number  647 non-null    str
 1   store_name    647 non-null    str
 2   street        647 non-null    str
 3   city          647 non-null    str
 4   state         647 non-null    str
 5   zip_code      647 non-null    str
 6   phone_number  647 non-null    str
 7   url           647 non-null    str
dtypes: str(8)
memory usage: 40.6 KB

### Add the data

In [5]:
upsert_dataframe_batch(df=df, table_name="stores", conflict_column="url", columns=STORE_COLUMNS)

Connected. Processing 647 rows in batches of 1000...
  Batch 1: 647 rows
✅ Completed: 647 total rows upserted

647

## Add data to the Internet Speed Table

In [2]:
from get_data.get_internet_speeds import get_internet_speeds_df

df = get_internet_speeds_df()

In [3]:
df.head()

,zip,population,county,state,wiredcount_2020,fwcount_2020,allprovidercount_2020,wired25_3_2020,wired100_3_2020,all25_3_2020,...,fastestaveragembps,access_terrestrial_broadband,lowest_priced_terrestrial_broadband,wiredcount_2015,fwcount_2015,allprovidercount_2015,wired25_3_2015,wired100_3_2015,all25_3_2015,all100_3_1
0,29620,12934,Abbeville,South Carolina,6,0,11,5,3,7,...,536.35,98%,40.00,6,0,8,3,3,3,3
1,29628,2759,Abbeville,South Carolina,4,0,8,3,2,5,...,126.06,95%,40.00,4,0,6,3,3,3,3
2,29638,2944,Abbeville,South Carolina,6,1,13,4,4,6,...,222.35,95%,40.00,5,0,7,2,2,2,2
3,29639,1742,Abbeville,South Carolina,3,0,8,3,3,5,...,223.75,90%,40.00,3,0,5,3,3,3,3
4,70516,1546,Acadia,Louisiana,4,3,12,2,2,4,...,9.41,33%,69.99,4,2,8,2,1,2,1

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32608 entries, 0 to 32607
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   zip                                  32608 non-null  str
 1   population                           29727 non-null  Int64
 2   county                               32608 non-null  str
 3   state                                32608 non-null  str
 4   wiredcount_2020                      29733 non-null  Int64
 5   fwcount_2020                         29733 non-null  Int64
 6   allprovidercount_2020                29733 non-null  Int64
 7   wired25_3_2020                       29733 non-null  Int64
 8   wired100_3_2020                      29733 non-null  Int64
 9   all25_3_2020                         29733 non-null  Int64
 10  all100_3_2020                        29733 non-null  Int64
 11  testcount                            26368 non-null  Int64
 12  averagembps                          26368 non-null  float64
 13  fastestaveragembps                   26368 non-null  float64
 14  access_terrestrial_broadband         29685 non-null  str
 15  lowest_priced_terrestrial_broadband  26630 non-null  float64
 16  wiredcount_2015                      29730 non-null  Int64
 17  fwcount_2015                         29730 non-null  Int64
 18  allprovidercount_2015                29730 non-null  Int64
 19  wired25_3_2015                       29730 non-null  Int64
 20  wired100_3_2015                      29730 non-null  Int64
 21  all25_3_2015                         29730 non-null  Int64
 22  all100_3_1                           29730 non-null  Int64
dtypes: Int64(16), float64(3), str(4)
memory usage: 6.2 MB

In [5]:
df.head()

,zip,population,county,state,wiredcount_2020,fwcount_2020,allprovidercount_2020,wired25_3_2020,wired100_3_2020,all25_3_2020,...,fastestaveragembps,access_terrestrial_broadband,lowest_priced_terrestrial_broadband,wiredcount_2015,fwcount_2015,allprovidercount_2015,wired25_3_2015,wired100_3_2015,all25_3_2015,all100_3_1
0,29620,12934,Abbeville,South Carolina,6,0,11,5,3,7,...,536.35,98%,40.00,6,0,8,3,3,3,3
1,29628,2759,Abbeville,South Carolina,4,0,8,3,2,5,...,126.06,95%,40.00,4,0,6,3,3,3,3
2,29638,2944,Abbeville,South Carolina,6,1,13,4,4,6,...,222.35,95%,40.00,5,0,7,2,2,2,2
3,29639,1742,Abbeville,South Carolina,3,0,8,3,3,5,...,223.75,90%,40.00,3,0,5,3,3,3,3
4,70516,1546,Acadia,Louisiana,4,3,12,2,2,4,...,9.41,33%,69.99,4,2,8,2,1,2,1

In [6]:
insert_df(df=df, table_name=INTERNET_SPEED_TABLE, columns=INTERNET_SPEED_COLUMNS)

✅ 32608 rows inserted in <1 second!